openapi: 3.2.0
info:
  title: Company Risk Scoring Scanning API
  version: 0.1.0
  description: '**Company Risk Scoring API v0.1.0**


    This API provides a comprehensive service for evaluating the cybersecurity risk associated with external companies, primarily identified by their domain name.'
tags:
- name: Scanning
paths:
  /api/b2b/crs/scan/submit/{domain}:
    post:
      tags:
      - Scanning
      summary: Submit Scan
      operationId: submit_scan_api_b2b_crs_scan_submit__domain__post
      security:
      - APIKeyHeader: []
      - HTTPBasic: []
      parameters:
      - name: domain
        in: path
        required: true
        schema:
          type: string
          title: Domain
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmitScanResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/b2b/crs/scan/jobs/{domain}:
    get:
      tags:
      - Scanning
      summary: Get Scan Jobs For Domain
      operationId: get_scan_jobs_for_domain_api_b2b_crs_scan_jobs__domain__get
      security:
      - APIKeyHeader: []
      - HTTPBasic: []
      parameters:
      - name: domain
        in: path
        required: true
        schema:
          type: string
          title: Domain
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScanJobsResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ScanJobResult:
      properties:
        id:
          type: string
          title: Id
        date_created:
          type: string
          format: date-time
          title: Date Created
        date_updated:
          type: string
          format: date-time
          title: Date Updated
        finished:
          type: boolean
          title: Finished
        cancelled:
          type: boolean
          title: Cancelled
          default: false
      type: object
      required:
      - id
      - date_created
      - date_updated
      - finished
      title: ScanJobResult
    SubmitScanResponse:
      properties:
        scan_job_id:
          type: string
          title: Scan Job Id
      type: object
      required:
      - scan_job_id
      title: SubmitScanResponse
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ScanJobsResponse:
      properties:
        domain:
          type: string
          title: Domain
        scan_jobs:
          items:
            $ref: '#/components/schemas/ScanJobResult'
          type: array
          title: Scan Jobs
      type: object
      required:
      - domain
      - scan_jobs
      title: ScanJobsResponse
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: X-API-Key
    HTTPBasic:
      type: http
      scheme: basic
